spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  application:
    name: port-and-adapters-architecture
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:~/hexagon;DATABASE_TO_UPPER=false;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=TRUE;IGNORECASE=TRUE
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        globally_quoted_identifiers: true
        dialect: org.hibernate.dialect.H2Dialect
    generate-ddl: false
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    locations: classpath:db/migration
logging:
  level:
    root: INFO
    demo.hexagon: INFO
adapter:
  driver:
    web:
      type: rest-api # possible types: rest-api
  driven:
    persistence:
      type: spring-data-jpa # possible types: spring-data-jpa | in-memory